# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

AdminUser.create([
  { :id => 1, :email => "christian@nikolajsen.net", :encrypted_password => "$2a$10$/wPSjGHmv3kowmwm5W8T8OeC7SzFbCh1Ulp4/eYnfB4RMUnrT8KBi", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => "2013-04-01 08:24:04", :sign_in_count => 9, :current_sign_in_at => "2013-04-01 08:24:04", :last_sign_in_at => "2013-03-29 10:49:12", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-03-07 11:43:12", :updated_at => "2013-04-01 08:24:04" }
], :without_protection => true )



Armor.create([
  { :id => 1, :name => "Heavy Clothing", :description => "Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum id ligula porta felis euismod semper. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.", :defense => 0, :soak => 1, :price => 50, :created_at => "2013-03-16 20:14:14", :updated_at => "2013-04-01 08:24:31" },
  { :id => 2, :name => "Padded Armor", :description => "", :defense => 0, :soak => 2, :price => 500, :created_at => "2013-03-16 20:14:50", :updated_at => "2013-03-16 20:14:50" },
  { :id => 3, :name => "Armored Clothing", :description => "", :defense => 1, :soak => 1, :price => 1000, :created_at => "2013-03-16 20:15:34", :updated_at => "2013-03-16 20:15:34" },
  { :id => 4, :name => "Heavy Battle Armor", :description => "", :defense => 1, :soak => 2, :price => 5000, :created_at => "2013-03-16 20:16:08", :updated_at => "2013-03-16 20:16:08" }
], :without_protection => true )



Career.create([
  { :id => 1, :name => "Bounty Hunter", :description => "<em>Reputation is everything</em>", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-09 06:32:48" },
  { :id => 2, :name => "Colonist", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" },
  { :id => 3, :name => "Explorer", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" },
  { :id => 4, :name => "Hired Gun", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" },
  { :id => 5, :name => "Smuggler", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" },
  { :id => 6, :name => "Technician", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" }
], :without_protection => true )



Gear.create([
  { :id => 1, :name => "Comlink", :description => "Comlinks allow for audio messaging between two parties. Some models are built into helmets and armor segments. Most operate on a standard set of frequencies that can be adjusted as desired to elude detection.", :price => 25, :created_at => "2013-03-14 18:34:45", :updated_at => "2013-03-14 18:34:45" },
  { :id => 2, :name => "Electroboniculars", :description => "", :price => 250, :created_at => "2013-03-14 18:38:20", :updated_at => "2013-03-14 18:38:20" },
  { :id => 3, :name => "Macrobinocluars", :description => "", :price => 75, :created_at => "2013-03-14 18:38:40", :updated_at => "2013-03-14 18:38:40" },
  { :id => 4, :name => "General Purpose Scanner", :description => "", :price => 500, :created_at => "2013-03-14 18:39:10", :updated_at => "2013-03-14 18:39:10" },
  { :id => 5, :name => "Hand Scanner", :description => "", :price => 100, :created_at => "2013-03-14 18:39:51", :updated_at => "2013-03-14 18:39:51" },
  { :id => 6, :name => "Emergency Medpac", :description => "", :price => 100, :created_at => "2013-03-14 18:40:07", :updated_at => "2013-03-14 18:40:07" },
  { :id => 7, :name => "Medpac", :description => "", :price => 400, :created_at => "2013-03-14 18:41:20", :updated_at => "2013-03-14 18:41:20" },
  { :id => 8, :name => "Stimpack", :description => "Stimpacks are auto-injection tubes filled with medicine, bacta, and painkillers. It takes a maneuver for a character to inject a stimpack in himself or another. A stimpack is a one use item.\r\nStimpacks heal a fixed amount with no roll necessary. Each stimpack used on a character automatically recovers four wounds. Stimpacks have no effect on Critical Injuries.", :price => 25, :created_at => "2013-03-14 18:42:32", :updated_at => "2013-03-14 19:08:50" },
  { :id => 9, :name => "Disguise Kit", :description => "", :price => 100, :created_at => "2013-03-14 18:47:33", :updated_at => "2013-03-14 18:47:33" },
  { :id => 10, :name => "Electronic Lock Breaker", :description => "", :price => 1000, :created_at => "2013-03-14 18:47:56", :updated_at => "2013-03-14 18:47:56" },
  { :id => 11, :name => "Binders", :description => "", :price => 25, :created_at => "2013-03-14 18:48:17", :updated_at => "2013-03-14 18:48:17" },
  { :id => 12, :name => "Restraining Bolt", :description => "", :price => 35, :created_at => "2013-03-14 18:48:58", :updated_at => "2013-03-14 18:48:58" },
  { :id => 13, :name => "Ration Pack", :description => "", :price => 5, :created_at => "2013-03-14 18:49:14", :updated_at => "2013-03-14 18:49:14" },
  { :id => 14, :name => "Breath Mask", :description => "", :price => 25, :created_at => "2013-03-14 18:49:35", :updated_at => "2013-03-14 18:49:35" },
  { :id => 15, :name => "Space Suit", :description => "", :price => 100, :created_at => "2013-03-14 18:50:25", :updated_at => "2013-03-14 18:50:25" },
  { :id => 16, :name => "Backpack", :description => "", :price => 50, :created_at => "2013-03-14 18:50:46", :updated_at => "2013-03-14 18:50:46" },
  { :id => 17, :name => "Datapad", :description => "", :price => 75, :created_at => "2013-03-14 18:52:35", :updated_at => "2013-03-14 18:52:35" },
  { :id => 18, :name => "Glow Rod", :description => "", :price => 10, :created_at => "2013-03-14 18:53:24", :updated_at => "2013-03-14 18:53:24" },
  { :id => 19, :name => "Extra Reloads", :description => "", :price => 25, :created_at => "2013-03-14 18:54:51", :updated_at => "2013-03-14 18:54:51" },
  { :id => 20, :name => "Power Packs", :description => "", :price => 25, :created_at => "2013-03-14 18:55:21", :updated_at => "2013-03-14 18:55:21" },
  { :id => 21, :name => "Tool Kit", :description => "", :price => 350, :created_at => "2013-03-14 18:55:37", :updated_at => "2013-03-14 18:55:37" },
  { :id => 22, :name => "Emergency Repair Kit", :description => "", :price => 25, :created_at => "2013-03-14 18:56:01", :updated_at => "2013-03-14 18:56:01" }
], :without_protection => true )



Race.create([
  { :id => 1, :name => "Bothan", :description => "", :wound_threshold => 10, :strain_threshold => 11, :starting_experience => 100, :special_ability => "", :brawn => 1, :cunning => 3, :presence => 2, :agility => 2, :intellect => 2, :willpower => 2, :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 21:00:31" },
  { :id => 2, :name => "Droid (class four)", :description => "", :wound_threshold => 10, :strain_threshold => 10, :starting_experience => 175, :special_ability => "", :brawn => 1, :cunning => 1, :presence => 1, :agility => 1, :intellect => 1, :willpower => 1, :created_at => "2013-03-08 21:02:06", :updated_at => "2013-03-08 21:02:06" },
  { :id => 7, :name => "Human", :description => "", :wound_threshold => nil, :strain_threshold => nil, :starting_experience => nil, :special_ability => "", :brawn => nil, :cunning => nil, :presence => nil, :agility => nil, :intellect => nil, :willpower => nil, :created_at => "2013-03-18 08:41:28", :updated_at => "2013-03-18 08:41:28" }
], :without_protection => true )



Skill.create([
  { :id => 1, :name => "Astrogation", :description => "", :characteristic => "Intellect", :created_at => "2013-03-09 12:55:51", :updated_at => "2013-03-09 13:06:23" },
  { :id => 2, :name => "Athletics", :description => "", :characteristic => "Brawn", :created_at => "2013-03-09 13:07:34", :updated_at => "2013-03-09 13:07:34" },
  { :id => 4, :name => "Brawl", :description => "", :characteristic => "Brawn", :created_at => "2013-03-09 13:08:14", :updated_at => "2013-03-09 13:08:14" },
  { :id => 3, :name => "Charm", :description => "", :characteristic => "Presence", :created_at => "2013-03-09 13:07:55", :updated_at => "2013-03-09 13:07:55" },
  { :id => 5, :name => "Coerce", :description => "", :characteristic => "Willpower", :created_at => "2013-03-09 13:08:43", :updated_at => "2013-03-09 13:08:43" },
  { :id => 6, :name => "Computers", :description => "", :characteristic => "Intellect", :created_at => "2013-03-09 13:08:59", :updated_at => "2013-03-09 13:08:59" },
  { :id => 7, :name => "Cool", :description => "", :characteristic => "Presence", :created_at => "2013-03-09 13:09:12", :updated_at => "2013-03-09 13:09:12" },
  { :id => 8, :name => "Coordination", :description => "", :characteristic => "Agility", :created_at => "2013-03-09 13:09:40", :updated_at => "2013-03-09 13:09:40" },
  { :id => 9, :name => "Deceit", :description => "", :characteristic => "Cunning", :created_at => "2013-03-09 13:09:57", :updated_at => "2013-03-09 13:09:57" },
  { :id => 10, :name => "Discipline", :description => "", :characteristic => "Willpower", :created_at => "2013-03-09 13:10:19", :updated_at => "2013-03-09 13:10:19" },
  { :id => 11, :name => "Gunnery", :description => "", :characteristic => "Agility", :created_at => "2013-03-09 13:43:04", :updated_at => "2013-03-09 13:43:04" },
  { :id => 12, :name => "Knowledge", :description => "", :characteristic => "Intellect", :created_at => "2013-03-15 13:59:50", :updated_at => "2013-03-15 13:59:50" },
  { :id => 13, :name => "Leadership", :description => "", :characteristic => "Presence", :created_at => "2013-03-15 14:02:21", :updated_at => "2013-03-15 14:02:21" },
  { :id => 14, :name => "Mechanics", :description => "", :characteristic => "Intellect", :created_at => "2013-03-15 14:02:37", :updated_at => "2013-03-15 14:02:37" },
  { :id => 15, :name => "Medicine", :description => "", :characteristic => "Intellect", :created_at => "2013-03-15 14:02:49", :updated_at => "2013-03-15 14:02:49" },
  { :id => 16, :name => "Melee", :description => "", :characteristic => "Intellect", :created_at => "2013-03-15 14:03:00", :updated_at => "2013-03-15 14:03:00" },
  { :id => 17, :name => "Negotiate", :description => "", :characteristic => "Presence", :created_at => "2013-03-15 14:03:15", :updated_at => "2013-03-15 14:03:15" },
  { :id => 18, :name => "Perception", :description => "", :characteristic => "Cunning", :created_at => "2013-03-15 14:03:31", :updated_at => "2013-03-15 14:03:31" },
  { :id => 19, :name => "Pilot", :description => "", :characteristic => "Agility", :created_at => "2013-03-15 14:03:46", :updated_at => "2013-03-15 14:03:46" },
  { :id => 20, :name => "Ranged (Heavy)", :description => "", :characteristic => "Agility", :created_at => "2013-03-15 14:04:06", :updated_at => "2013-03-15 14:04:06" },
  { :id => 21, :name => "Ranged (Light)", :description => "", :characteristic => "Agility", :created_at => "2013-03-15 14:04:21", :updated_at => "2013-03-15 14:04:21" },
  { :id => 22, :name => "Resilience", :description => "", :characteristic => "Brawn", :created_at => "2013-03-15 14:04:40", :updated_at => "2013-03-15 14:04:40" },
  { :id => 23, :name => "Skulduggery", :description => "", :characteristic => "Cunning", :created_at => "2013-03-15 14:05:12", :updated_at => "2013-03-15 14:05:12" },
  { :id => 24, :name => "Stealth", :description => "", :characteristic => "Agility", :created_at => "2013-03-15 14:05:34", :updated_at => "2013-03-15 14:05:34" },
  { :id => 25, :name => "Streetwise", :description => "", :characteristic => "Cunning", :created_at => "2013-03-15 14:05:46", :updated_at => "2013-03-15 14:05:46" },
  { :id => 26, :name => "Survival", :description => "", :characteristic => "Cunning", :created_at => "2013-03-15 14:05:59", :updated_at => "2013-03-15 14:05:59" },
  { :id => 27, :name => "Vigilance", :description => "", :characteristic => "Willpower", :created_at => "2013-03-15 14:06:12", :updated_at => "2013-03-15 14:06:12" }
], :without_protection => true )



Talent.create([
  { :id => 1, :name => "Grit", :description => "Gain +1 strain threshold.\r\n\r\nEach rank of Grit increases a character’s strain threshold by 1.", :activation => "Passive", :ranked => false, :cost => 0, :specialization_id => 1, :talent_type => "", :created_at => "2013-03-09 05:27:28", :updated_at => "2013-03-18 08:19:26" },
  { :id => 2, :name => "Anatomy Lessons", :description => "", :activation => "Active (Incidental)", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:13:33", :updated_at => "2013-03-18 08:13:33" },
  { :id => 3, :name => "Armor Master", :description => "", :activation => "Passive", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:14:00", :updated_at => "2013-03-18 08:14:00" },
  { :id => 4, :name => "Barrage", :description => "", :activation => "Passive", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:14:17", :updated_at => "2013-03-18 08:14:17" },
  { :id => 5, :name => "Body Guard", :description => "", :activation => "Active (Maneuver)", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:14:54", :updated_at => "2013-03-18 08:14:54" },
  { :id => 6, :name => "Body Guard (Improved)", :description => "", :activation => "Active (Maneuver)", :ranked => false, :cost => 0, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:15:19", :updated_at => "2013-03-18 08:15:19" },
  { :id => 7, :name => "Dodge", :description => "", :activation => "Active (Incidental, Out of Turn)", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:15:57", :updated_at => "2013-03-18 08:15:57" },
  { :id => 8, :name => "Enduring", :description => "Character gains +1 soak value per rank of Enduring.", :activation => "Passive", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:16:57", :updated_at => "2013-03-18 08:16:57" },
  { :id => 9, :name => "Expert Tracker", :description => "", :activation => "Passive", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:17:16", :updated_at => "2013-03-18 08:17:16" },
  { :id => 10, :name => "Feral Strength", :description => "", :activation => "Passive", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:17:35", :updated_at => "2013-03-18 08:17:35" },
  { :id => 11, :name => "Field Commander", :description => "", :activation => "Active (Action)", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:17:57", :updated_at => "2013-03-18 08:17:57" },
  { :id => 12, :name => "Full Throttle", :description => "", :activation => "Active (Action)", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:18:31", :updated_at => "2013-03-18 08:18:31" },
  { :id => 13, :name => "Full Throttle (Improved)", :description => "", :activation => "Active (Maneuver)", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:18:55", :updated_at => "2013-03-18 08:18:55" },
  { :id => 14, :name => "Hidden Storage", :description => "", :activation => "Passive", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:21:18", :updated_at => "2013-03-18 08:21:18" },
  { :id => 15, :name => "Inspiring Rhetoric", :description => "", :activation => "Active (Action)", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:21:57", :updated_at => "2013-03-18 08:21:57" },
  { :id => 16, :name => "Jump Up", :description => "", :activation => "Active (Incidental)", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:22:35", :updated_at => "2013-03-18 08:22:35" },
  { :id => 17, :name => "Jury Rigged", :description => "", :activation => "Passive", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:22:58", :updated_at => "2013-03-18 08:22:58" },
  { :id => 18, :name => "Kill with Kindness", :description => "", :activation => "Passive", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:23:34", :updated_at => "2013-03-18 08:23:34" },
  { :id => 19, :name => "Knockdown", :description => "", :activation => "Passive", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:24:14", :updated_at => "2013-03-18 08:24:14" },
  { :id => 20, :name => "Natural Charmer", :description => "", :activation => "Active (Free Action)", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:24:49", :updated_at => "2013-03-18 08:24:49" },
  { :id => 21, :name => "Point Blank", :description => "", :activation => "Passive", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:25:24", :updated_at => "2013-03-18 08:25:24" },
  { :id => 22, :name => "Precise Aim", :description => "", :activation => "Active (Maneuver)", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:25:49", :updated_at => "2013-03-18 08:25:49" },
  { :id => 23, :name => "Quick Draw", :description => "", :activation => "Active (Incidental)", :ranked => false, :cost => nil, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:26:20", :updated_at => "2013-03-18 08:26:20" },
  { :id => 24, :name => "Quick Strike", :description => "", :activation => "Passive", :ranked => false, :cost => 0, :specialization_id => nil, :talent_type => "", :created_at => "2013-03-18 08:26:43", :updated_at => "2013-03-18 08:26:43" }
], :without_protection => true )



TalentTree.create([
  { :id => 1, :name => "Smuggler", :description => "sfsdfsd", :talent_1_1 => 1, :talent_1_2 => nil, :talent_1_3 => nil, :talent_1_4 => 23, :talent_2_1 => 20, :talent_2_2 => 12, :talent_3_3 => nil, :talent_4_4 => nil, :talent_3_1 => nil, :talent_3_2 => 13, :talent_3_4 => nil, :talent_4_1 => nil, :talent_4_2 => nil, :talent_4_3 => nil, :created_at => "2013-03-17 14:20:34", :updated_at => "2013-03-29 11:05:56", :talent_2_3 => 14, :talent_2_4 => 24, :career_id => 5 },
  { :id => 2, :name => "Explorer", :description => "", :talent_1_1 => nil, :talent_1_2 => nil, :talent_1_3 => nil, :talent_1_4 => nil, :talent_2_1 => nil, :talent_2_2 => nil, :talent_3_3 => nil, :talent_4_4 => nil, :talent_3_1 => nil, :talent_3_2 => nil, :talent_3_4 => nil, :talent_4_1 => nil, :talent_4_2 => nil, :talent_4_3 => nil, :created_at => "2013-03-25 12:08:44", :updated_at => "2013-03-25 12:08:44", :talent_2_3 => nil, :talent_2_4 => nil, :career_id => 3 }
], :without_protection => true )



TalentTreeCareerSkill.create([
  { :id => 1, :talent_tree_id => 1, :skill_id => 1, :created_at => "2013-03-17 14:24:41", :updated_at => "2013-03-17 14:24:41" },
  { :id => 2, :talent_tree_id => 1, :skill_id => 3, :created_at => "2013-03-17 14:31:01", :updated_at => "2013-03-17 14:31:01" },
  { :id => 3, :talent_tree_id => 1, :skill_id => 8, :created_at => "2013-03-17 14:32:22", :updated_at => "2013-03-17 14:32:22" },
  { :id => 4, :talent_tree_id => 1, :skill_id => 9, :created_at => "2013-03-17 15:06:09", :updated_at => "2013-03-17 15:06:09" },
  { :id => 5, :talent_tree_id => 1, :skill_id => 12, :created_at => "2013-03-17 15:06:09", :updated_at => "2013-03-17 15:06:09" },
  { :id => 6, :talent_tree_id => 1, :skill_id => 18, :created_at => "2013-03-17 15:07:22", :updated_at => "2013-03-17 15:07:22" },
  { :id => 7, :talent_tree_id => 1, :skill_id => 19, :created_at => "2013-03-17 15:07:22", :updated_at => "2013-03-17 15:07:22" },
  { :id => 8, :talent_tree_id => 1, :skill_id => 23, :created_at => "2013-03-17 15:07:22", :updated_at => "2013-03-17 15:07:22" },
  { :id => 9, :talent_tree_id => 1, :skill_id => 25, :created_at => "2013-03-17 15:07:22", :updated_at => "2013-03-17 15:07:22" },
  { :id => 10, :talent_tree_id => 1, :skill_id => 27, :created_at => "2013-03-17 15:07:22", :updated_at => "2013-03-17 15:07:22" },
  { :id => 11, :talent_tree_id => 1, :skill_id => 11, :created_at => "2013-03-17 15:07:22", :updated_at => "2013-03-17 15:07:22" }
], :without_protection => true )



Weapon.create([
  { :id => 1, :name => "Holdout Blaster", :description => "", :skill_id => 21, :damage => 5, :crit => 4, :price => 300, :created_at => "2013-03-15 13:31:08", :updated_at => "2013-03-15 14:41:40", :range => "Short" },
  { :id => 2, :name => "Light Blaster Pistol", :description => "", :skill_id => 21, :damage => 5, :crit => 4, :price => 400, :created_at => "2013-03-15 15:00:45", :updated_at => "2013-03-15 15:00:45", :range => "Medium" },
  { :id => 3, :name => "Blaster Pistol", :description => "", :skill_id => 21, :damage => 6, :crit => 3, :price => 500, :created_at => "2013-03-15 15:30:54", :updated_at => "2013-03-15 15:30:54", :range => "Medium" },
  { :id => 4, :name => "Heavy Blaster Pistol", :description => "Heavy blaster are very powerful. Their only major drawback is that they carry less shots than either, a trade-off for the increased power. Game Masters can spend one Despair [des] to have a heavy blaster pistol run out of ammo.", :skill_id => 20, :damage => 7, :crit => 3, :price => 750, :created_at => "2013-03-15 15:32:39", :updated_at => "2013-03-17 05:03:56", :range => "Medium" },
  { :id => 5, :name => "Blaster Carbine", :description => "", :skill_id => 20, :damage => 9, :crit => 5, :price => 500, :created_at => "2013-03-15 21:54:03", :updated_at => "2013-03-15 21:54:03", :range => "Medium" },
  { :id => 6, :name => "Blaster Rifle", :description => "", :skill_id => 20, :damage => 9, :crit => 3, :price => 900, :created_at => "2013-03-15 21:55:27", :updated_at => "2013-03-15 21:55:40", :range => "Long" },
  { :id => 7, :name => "Heavy Repeating Blaster", :description => "", :skill_id => 11, :damage => 15, :crit => 2, :price => 6000, :created_at => "2013-03-15 21:56:37", :updated_at => "2013-03-15 21:56:37", :range => "Long" },
  { :id => 8, :name => "Bowcaster", :description => "", :skill_id => 20, :damage => 10, :crit => 3, :price => 1500, :created_at => "2013-03-15 21:57:46", :updated_at => "2013-03-15 21:57:46", :range => "Medium" }
], :without_protection => true )



WeaponQuality.create([
  { :id => 1, :name => "Auto-fire", :trigger => "Active", :description => "An auto-fire weapon has the chance to hit multiple targets or strike a single target multiple times but with sacrifices accuracy. The attacker must increase the difficulty of his attack roll by one (add one difficulty die [dif] to the attack roll).\r\nAuto-fire requires one Advantage [adv] to activate, and can be activated multiple times. Each time it does so, the weapon deals an additional hit to the target or another target engaged with the first target. Each of these count as an additional hit from that weapon, and each hit deals base damage plus the number of total Successes [suc] scored on the check.\r\nNote that each target can never suffer more Criticals than the number of times he was hit by the weapon.", :created_at => "2013-03-15 10:29:21", :updated_at => "2013-03-15 12:42:56" },
  { :id => 2, :name => "Breach", :trigger => "Passive", :description => "Breach weapons ignore one point of armor (on starships and vehicles) for every rating of Breach. They also ignore 10 points of soak for every rating of Breach.", :created_at => "2013-03-15 13:15:01", :updated_at => "2013-03-15 13:15:01" },
  { :id => 3, :name => "Blast", :trigger => "Active", :description => "", :created_at => "2013-03-15 13:16:04", :updated_at => "2013-03-15 13:16:04" },
  { :id => 4, :name => "Cumbersome", :trigger => "Passive", :description => "", :created_at => "2013-03-15 13:17:56", :updated_at => "2013-03-15 13:17:56" },
  { :id => 5, :name => "Disorient", :trigger => "Active", :description => "", :created_at => "2013-03-15 13:25:21", :updated_at => "2013-03-15 13:25:21" },
  { :id => 6, :name => "Knockdown", :trigger => "Active", :description => "", :created_at => "2013-03-15 13:27:30", :updated_at => "2013-03-15 13:27:30" },
  { :id => 7, :name => "Ion", :trigger => "Passive", :description => "", :created_at => "2013-03-15 13:27:41", :updated_at => "2013-03-15 13:27:41" },
  { :id => 8, :name => "Limited Ammo", :trigger => "Passive", :description => "", :created_at => "2013-03-15 13:28:08", :updated_at => "2013-03-15 13:28:08" },
  { :id => 9, :name => "Linked", :trigger => "Active", :description => "", :created_at => "2013-03-15 13:28:18", :updated_at => "2013-03-15 13:28:18" },
  { :id => 10, :name => "Pierce", :trigger => "Passive", :description => "", :created_at => "2013-03-15 13:28:59", :updated_at => "2013-03-15 13:28:59" },
  { :id => 11, :name => "Stun Damage", :trigger => "Passive", :description => "", :created_at => "2013-03-15 13:29:24", :updated_at => "2013-03-15 13:29:39" },
  { :id => 12, :name => "Stun Setting", :trigger => "Active", :description => "", :created_at => "2013-03-15 21:17:33", :updated_at => "2013-03-15 21:17:33" }
], :without_protection => true )



WeaponQualityRank.create([
  { :id => 1, :weapon_id => 1, :weapon_quality_id => 12, :ranks => 0, :created_at => "2013-03-16 06:33:02", :updated_at => "2013-03-16 18:42:51" },
  { :id => 2, :weapon_id => 8, :weapon_quality_id => 4, :ranks => 3, :created_at => "2013-03-16 18:44:12", :updated_at => "2013-03-16 18:44:12" },
  { :id => 3, :weapon_id => 8, :weapon_quality_id => 6, :ranks => 0, :created_at => "2013-03-16 18:44:25", :updated_at => "2013-03-16 18:44:25" },
  { :id => 4, :weapon_id => 2, :weapon_quality_id => 12, :ranks => 0, :created_at => "2013-03-16 19:03:30", :updated_at => "2013-03-16 19:03:30" },
  { :id => 5, :weapon_id => 3, :weapon_quality_id => 12, :ranks => 0, :created_at => "2013-03-16 19:04:09", :updated_at => "2013-03-16 19:04:09" },
  { :id => 6, :weapon_id => 4, :weapon_quality_id => 12, :ranks => 0, :created_at => "2013-03-16 19:04:38", :updated_at => "2013-03-16 19:04:38" },
  { :id => 7, :weapon_id => 5, :weapon_quality_id => 12, :ranks => 0, :created_at => "2013-03-16 19:04:55", :updated_at => "2013-03-16 19:04:55" },
  { :id => 8, :weapon_id => 6, :weapon_quality_id => 12, :ranks => 0, :created_at => "2013-03-16 19:05:11", :updated_at => "2013-03-16 19:05:11" },
  { :id => 9, :weapon_id => 7, :weapon_quality_id => 1, :ranks => 0, :created_at => "2013-03-16 19:05:32", :updated_at => "2013-03-16 19:05:32" },
  { :id => 10, :weapon_id => 7, :weapon_quality_id => 10, :ranks => 2, :created_at => "2013-03-16 19:05:51", :updated_at => "2013-03-16 19:05:51" },
  { :id => 11, :weapon_id => 7, :weapon_quality_id => 4, :ranks => 5, :created_at => "2013-03-16 19:06:24", :updated_at => "2013-03-16 19:06:24" }
], :without_protection => true )


