# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Career.create([
  { :id => 1, :name => "Bounty Hunter", :description => "<em>Reputation is everything</em>", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-09 06:32:48" },
  { :id => 2, :name => "Colonist", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" },
  { :id => 3, :name => "Explorer", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" },
  { :id => 4, :name => "Hired Gun", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" },
  { :id => 5, :name => "Smuggler", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" },
  { :id => 6, :name => "Technician", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" }
], :without_protection => true )



Race.create([
  { :id => 1, :name => "Bothan", :description => "", :wound_threshold => 10, :strain_threshold => 11, :starting_experience => 100, :special_ability => "", :brawn => 1, :cunning => 3, :presence => 2, :agility => 2, :intellect => 2, :willpower => 2, :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 21:00:31" },
  { :id => 2, :name => "Droid (class four)", :description => "", :wound_threshold => 10, :strain_threshold => 10, :starting_experience => 175, :special_ability => "", :brawn => 1, :cunning => 1, :presence => 1, :agility => 1, :intellect => 1, :willpower => 1, :created_at => "2013-03-08 21:02:06", :updated_at => "2013-03-08 21:02:06" }
], :without_protection => true )



Skill.create([
  { :id => nil, :name => nil, :description => nil, :characteristic => nil, :type => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Specialization.create([
  { :id => 1, :name => "Assassin", :description => "Instrument of Policy", :created_at => "2013-03-09 05:23:34", :updated_at => "2013-03-09 05:23:34", :career_id => 1 }
], :without_protection => true )



Talent.create([
  { :id => 1, :name => "Grit", :description => "Gain +1 strain threshold.\r\n\r\nEach rank of Grit increases a character’s strain threshold by 1.", :activation => "Passive", :ranked => true, :cost => 5, :specialization_id => 1, :talent_type => "", :created_at => "2013-03-09 05:27:28", :updated_at => "2013-03-09 05:27:28" }
], :without_protection => true )



User.create([
  { :id => 1, :username => "", :email => "cn@peytz.dk", :password_hash => "", :password_salt => "", :first_name => "", :last_name => "", :city => "", :state => "", :postal_code => "", :country_id => 0, :enabled => true, :notes => nil, :created_at => "2013-03-08 13:20:14", :updated_at => "2013-03-08 14:19:56", :encrypted_password => "$2a$10$60KdxgtOE7m2nOso2u5gi.481zFDfQ3Yh//pTZm9jyLDYpOX5U7qG", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 3, :current_sign_in_at => "2013-03-08 14:19:56", :last_sign_in_at => "2013-03-08 14:04:50", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1" }
], :without_protection => true )


