# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Race.delete_all
Race.create([
  { :id => 1, :name => "Bothan", :description => "", :wound_threshold => 10, :strain_threshold => 11, :starting_experience => 100, :special_ability => "", :brawn => 1, :cunning => 3, :presence => 2, :agility => 2, :intellect => 2, :willpower => 2, :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 21:00:31" },
  { :id => 2, :name => "Droid (class four)", :description => "", :wound_threshold => 10, :strain_threshold => 10, :starting_experience => 175, :special_ability => "", :brawn => 1, :cunning => 1, :presence => 1, :agility => 1, :intellect => 1, :willpower => 1, :created_at => "2013-03-08 21:02:06", :updated_at => "2013-03-08 21:02:06" }
], :without_protection => true )

Career.delete_all
Career.create([
  { :id => 1, :name => "Bounty Hunter", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" },
  { :id => 2, :name => "Colonist", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" },
  { :id => 3, :name => "Explorer", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" },
  { :id => 4, :name => "Hired Gun", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" },
  { :id => 5, :name => "Smuggler", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" },
  { :id => 6, :name => "Technician", :description => "", :created_at => "2013-03-08 20:58:49", :updated_at => "2013-03-08 20:58:49" }
], :without_protection => true )

